language: minimal
os: linux
arch: amd64
dist: bionic
branches: 
  except:
    - CI-latest
script:
- wget https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz
- gzip -d ow-snapshot.tar.gz
- mkdir _watcom
- mkdir _out
- mkdir _out/sdk
- mkdir _out/sdk/pcgeos
- cd _watcom
- tar -xf ../ow-snapshot.tar
- cd ..
- export PATH=$TRAVIS_BUILD_DIR/bin:$PATH:$TRAVIS_BUILD_DIR/_watcom/binl64
- export WATCOM=$TRAVIS_BUILD_DIR/_watcom
- export ROOT_DIR=$TRAVIS_BUILD_DIR
- export LOCAL_ROOT=$TRAVIS_BUILD_DIR/_out
- cd $TRAVIS_BUILD_DIR/Tools/pmake/pmake
- wmake install | tee $TRAVIS_BUILD_DIR/_build.log
- cd $TRAVIS_BUILD_DIR/Installed/Tools
- pmake install | tee -a $TRAVIS_BUILD_DIR/_build.log
- cd $TRAVIS_BUILD_DIR/Installed
- pmake -L 4 | tee -a $TRAVIS_BUILD_DIR/_build.log | grep -i -v "esp \|goc \|wcc \|wcc32 \|warning\|watcom\|--- "
- cd $TRAVIS_BUILD_DIR/Tools/sdk
- ./makesdk $TRAVIS_BUILD_DIR/_out/sdk/pcgeos | tee -a $TRAVIS_BUILD_DIR/_build.log
- cd $TRAVIS_BUILD_DIR/_out/sdk
- mkdir pcgeos/target
- mkdir pcgeos/target/ensemble.ec
- mkdir pcgeos/target/ensemble.nc
- cd $TRAVIS_BUILD_DIR/Tools/build/product/bbxensem/Scripts
- echo nt >$TRAVIS_BUILD_DIR/_temp.dat
- echo y >>$TRAVIS_BUILD_DIR/_temp.dat
- echo n >>$TRAVIS_BUILD_DIR/_temp.dat
- echo y >>$TRAVIS_BUILD_DIR/_temp.dat
- echo n >>$TRAVIS_BUILD_DIR/_temp.dat
- echo $TRAVIS_BUILD_DIR/_out/sdk/target/ensemble.ec >> $TRAVIS_BUILD_DIR/_temp.dat
- perl -I. buildbbx.pl  <$TRAVIS_BUILD_DIR/_temp.dat
- cd $TRAVIS_BUILD_DIR/Tools/build/product/bbxensem/Scripts
- echo nt >$TRAVIS_BUILD_DIR/_temp.dat
- echo n >>$TRAVIS_BUILD_DIR/_temp.dat
- echo n >>$TRAVIS_BUILD_DIR/_temp.dat
- echo y >>$TRAVIS_BUILD_DIR/_temp.dat
- echo n >>$TRAVIS_BUILD_DIR/_temp.dat
- echo $TRAVIS_BUILD_DIR/_out/sdk/target/ensemble.nc >> $TRAVIS_BUILD_DIR/_temp.dat
- perl -I. buildbbx.pl  <$TRAVIS_BUILD_DIR/_temp.dat
- cd $TRAVIS_BUILD_DIR/_out/sdk
- mv pcgeos/target pcgeos/Target
- mv pcgeos/Target/ensemble.ec pcgeos/Target/Ensemble.ec
- mv pcgeos/Target/ensemble.nc pcgeos/Target/Ensemble.nc
- zip -rq sdk.zip pcgeos 
before_deploy:
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    export TRAVIS_TAG=CI-latest
  fi
deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file: 
  - $TRAVIS_BUILD_DIR/_build.log
  - $TRAVIS_BUILD_DIR/_out/sdk/sdk.zip
  skip_cleanup: true
  prerelease: true
  draft: false
  overwrite: true
  on:
    tags: false
    branch: master
